name: My Template
description: Issue to json
title: "Issue to json!"
labels: my-template
body:
  - type: markdown
    attributes:
      value: |
        Only the site URL is required. All other fields are optional.
  - type: input
    id: input1
    attributes:
      label: Label1
      description: Label 1 description
      placeholder: type somethink
    validations:
      required: true
  - type: input
    id: input2
    attributes:
      label: Label2
      description: Label 2 description
      placeholder: type somethink
    validations:
      required: true